FROM zpp-dockerinio as new_compiled
WORKDIR /home

RUN pip3 install scipy

# Get repository.
COPY . deepmath/
RUN cd deepmath

# Configure tensorflow.
RUN cd deepmath/tensorflow && \
  TF_IGNORE_MAX_BAZEL_VERSION=1 \
  TF_NEED_OPENCL_SYCL=0 \
  TF_NEED_COMPUTECPP=1 \
  TF_NEED_ROCM=0 \
  TF_NEED_CUDA=0 \
  TF_ENABLE_XLA=0 \
  TF_DOWNLOAD_CLANG=0 \
  TF_NEED_MPI=0 \
  TF_SET_ANDROID_WORKSPACE=0 \
  CC_OPT_FLAGS="-march=native -Wno-sign-compare" \
  ./configure

# Build deepmath.
# Note: PYTHON_BIN_PATH and --python_path are both necessary.
RUN cd deepmath && \
  bazel build -c opt //deepmath/deephol:main --define grpc_no_ares=true --python_path=$PYTHON_BIN_PATH

# Make a copy without symlinks.
RUN cp -R -L /home/deepmath/bazel-bin/deepmath/deephol/main.runfiles /home/runfiles

# Get dependencies.

#RUN pip3 i#nstall h5py six numpy wheel mock pyfarmhash grpcio scipy 

# Set deephol:main as entrypoint.
ENTRYPOINT ["/home/deepmath/bazel-bin/deepmath/deephol/main"]
